---
# tasks file for tomcat
  - debug: msg="Will install tomcat"
  - name: Installing tomcat
    yum: name=tomcat state=installed
  - name: Installing tomcat apps
    yum:
      name: tomcat-webapps 
      state: installed
  - name: Changing ports for tomcat
    copy: src=server.xml dest=/usr/share/tomcat/conf/server.xml
    notify:
      - restart tomcat
  - name: Changing users for tomcat
    copy: src=tomcat-users.xml dest=/usr/share/tomcat/conf/tomcat-users.xml
    notify:
      - restart tomcat
  - name: deploy_folder
    file: path=/var/lib/tomcat/webapps state=directory recurse=yes mode=0777
  
  - name: Start Tomcat
    service: name=tomcat state=started enabled=yes
