# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

srcdir=.
top_srcdir=..
top_builddir=..
APXS=/usr/sbin/apxs
CP=/bin/cp
APACHE_DIR=/etc/httpd
MKDIR=/bin/mkdir
APXSCFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wformat-security -fno-strict-aliasing -pthread -DHAVE_APR  -I/usr/include/apr-1 -I/usr/include/apr-1  -DHAVE_CONFIG_H
APXSCPPFLAGS=-DLINUX=2 -D_REENTRANT -D_GNU_SOURCE
APXSLDFLAGS=
CC=gcc
SHELL=/bin/sh

# Defaults
libexecdir=${APACHE_DIR}/modules

JK=${top_builddir}/common/
# Defines APACHE_OBJECTS - the list of all common files
include ${top_builddir}/common/list.mk

# Apache settings, values guessed by Apache config and used to build it
# Will define libexecdir, LIBTOOL, etc
include /usr/lib64/httpd/build/config_vars.mk

# Local settings ( overriding/appending to Apache's )
COMMON=common
JK_INCL=-DUSE_APACHE_MD5 -I${top_builddir}/${COMMON} -I ${top_srcdir}/${COMMON}
CFLAGS=-I/usr/include/httpd  -DHAVE_CONFIG_H ${JK_INCL} ${APXSCPPFLAGS} ${APXSCFLAGS} ${EXTRA_CFLAGS} ${EXTRA_CPPFLAGS}


# Implicit rules
include ${top_srcdir}/scripts/build/rules.mk

OEXT=.lo

all: Makefile mod_jk.so
install: install_dynamic

Makefile: ${srcdir}/Makefile.in
	echo Regenerating Makefile
	( cd ..; ./config.status )

lib_jk.la: mod_jk.lo ${APACHE_OBJECTS}
	$(LIBTOOL) --mode=link $(CC) -o lib_jk.la -static -rpath ${libexecdir}/jk mod_jk.lo $(APACHE_OBJECTS)

install_static:
	@echo ""
	@echo "Copying files to Apache Modules Directory..."
	-${MKDIR} ${APACHE_DIR}/modules/jk
	${CP} config.m4 ${APACHE_DIR}/modules/jk
	${LIBTOOL} --mode=install cp lib_jk.la ${APACHE_DIR}/modules/jk
	@echo ""
	@echo "Please be sure to re-compile Apache..."
	@echo ""
	@echo "cd ${APACHE_DIR}"
	@echo "./buildconf"
	@echo "./configure --with-mod_jk"
	@echo "make"
	@echo ""

#################### Dynamic .so file ####################
# APXS will compile every file, this is derived from apxs

mod_jk.lo: ${srcdir}/mod_jk.c
	${LT_COMPILE}

mod_jk.la: mod_jk.lo $(APACHE_OBJECTS)
	$(LIBTOOL) --mode=link ${COMPILE} $(APXSLDFLAGS) -o $@ -module -rpath ${libexecdir} -avoid-version mod_jk.lo $(APACHE_OBJECTS)

mod_jk.so: mod_jk.la
	${top_srcdir}/scripts/build/instdso.sh SH_LIBTOOL='$(LIBTOOL)' mod_jk.la `pwd`

install_dynamic:
	@echo ""
	@echo "Installing files to Apache Modules Directory..."
	$(APXS) -i mod_jk.la
	@echo ""
	@echo "Please be sure to arrange ${APACHE_DIR}/conf/httpd.conf..."
	@echo ""

clean:
	rm -f *.o *.lo *.a *.la *.so *.so.* *.slo
	rm -rf .libs

maintainer-clean: clean

distclean: clean
