- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    services_info: |
      Jenkins_URL: "http://localhost:9080/jenkins/"
      Application_URL: "http://localhost:8080/mnt-lab/"
      tomcat_port: "9090"
      nginx_port: "8080"
      jenkins_port: "9080"
      java_pack_version: "java-1.7.0-openjdk-devel"
      jenkins_home: "/var/lib/jenkins"
  pre_tasks:
  - debug: msg="Let's do this"

  roles:
  - jenkins
  - tomcat
  - nginx

  post_tasks:
  - debug: var=services_info.split('\n')
